--- STADIUM
SELECT  lower(EMAIL_ADDRESS) AS EMAIL, EVENT_DATE
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022')
AND (EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN')
AND CAN_CONTACT_EMAIL = TRUE 
AND EMAIL_ADDRESS like '%@%'
AND  PRICE_TYPE_NAME not iLIKE '%Ground Pass%'
GROUP BY EVENT_DATE, lower(EMAIL_ADDRESS) 
HAVING EVENT_DATE = '2022-01-29'-- IN ('2022-01-18', '2022-01-20', '2022-01-22', '2022-01-23', '2022-01-25', '2022-01-28')
ORDER BY EVENT_DATE

-- GROUND PASS
SELECT  lower(EMAIL_ADDRESS) AS EMAIL, EVENT_DATE
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022')
AND (EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN')
AND CAN_CONTACT_EMAIL = TRUE 
AND EMAIL_ADDRESS like '%@%'
AND  PRICE_TYPE_NAME iLIKE '%Ground Pass%'
GROUP BY EVENT_DATE, lower(EMAIL_ADDRESS) 
HAVING EVENT_DATE = '2022-01-29'-- IN ('2022-01-18', '2022-01-20', '2022-01-22', '2022-01-23', '2022-01-25', '2022-01-28')
ORDER BY EVENT_DATE

--AO daily purchase
SELECT  lower(EMAIL_ADDRESS) AS EMAIL, EVENT_DATE
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022')
AND (EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN')
AND CAN_CONTACT_EMAIL = TRUE 
AND EMAIL_ADDRESS like '%@%'
GROUP BY EVENT_DATE, lower(EMAIL_ADDRESS) 
HAVING EVENT_DATE = '2022-01-29'
ORDER BY EVENT_DATE 

--Exclusion List
SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'

-- Previous Ground Pass ticket holders (2021, 2020, 2019)
SELECT  lower(EMAIL_ADDRESS) AS EMAIL
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where  EVENT_TOURNAMENT_SERIES_YEAR IN ('2019','2020','2021')
AND (EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN')
AND CAN_CONTACT_EMAIL = TRUE 
AND EMAIL_ADDRESS like '%@%'
AND  PRICE_TYPE_NAME LIKE '%Ground Pass%'

--AO 22 ticket holders from 24 Jan to 30 Jan, excluding PX bookers
SELECT * FROM
(
SELECT  lower(EMAIL_ADDRESS) AS EMAIL, EVENT_DATE, DATA_HASH
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022')
AND (EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN')
AND CAN_CONTACT_EMAIL = TRUE 
AND EMAIL_ADDRESS like '%@%'
GROUP BY EVENT_DATE,DATA_HASH,lower(EMAIL_ADDRESS) 
HAVING EVENT_DATE IN ('2022-01-24','2022-01-25','2022-01-26','2022-01-27','2022-01-28','2022-01-29','2022-01-30') 
ORDER BY EVENT_DATE
  ) A
WHERE A.EMAIL NOT IN 
(SELECT DISTINCT EMAIL FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_PX_CUSTOMERS_BLACKLIST")

select distinct price_type_name FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where price_type_name like '%premium%'

----ALL AO 2022 PURCHASES OPTIN
SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE

--1. AO22 ticket purchasers
--2. Shopify database

SELECT DISTINCT EMAIL, SOURCE, STATE, COUNTRY
FROM
( SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
(SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY, '1' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
UNION
SELECT DISTINCT LOWER (S.CUSTOMER_EMAIL) AS EMAIL, 'SHOPIFY' AS SOURCE, SHIPPING_REGION AS STATE, SHIPPING_COUNTRY AS COUNTRY ,'2' AS PRIORITY
FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_MERCHANDISE_SALE" S
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."RPT_MERCHANDISE_CUSTOMER" C
ON S.CUSTOMER_EMAIL = C.EMAIL
WHERE S.CUSTOMER_EMAIL like '%@%'
AND C.ACCEPTS_MARKETING ='yes'
 )A
 )B
 WHERE B.ROW_NUMBER=1

SELECT DISTINCT ACCEPTS_MARKETING FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_MERCHANDISE_CUSTOMER" C



--Court hire booking past 3 months 1. Email2. Source3. State4. Country
SELECT EMAIL,SOURCE,STATE,COUNTRY 
FROM(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE, CONTACT_COUNTY AS STATE, CONTACT_COUNTRY AS COUNTRY,BOOKINGSESSIONDATE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE USER_CANSENDOFFERS ='Yes'
AND BOOKINGSESSIONDATE between  dateadd(MONTH, -3, current_date) and CURRENT_DATE() 
order by BOOKINGSESSIONDATE)

--Court hire bookers - 12 months
--Cardio tennis bookers - 12 months
--ANZ Hot Shots - 12 months
--FIELDS-> 1. Email 2. Source 3. State 4. Country
SELECT EMAIL,SOURCE,STATE,COUNTRY 
FROM(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE, CONTACT_COUNTY AS STATE, CONTACT_COUNTRY AS COUNTRY
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE USER_CANSENDOFFERS ='Yes'
AND BOOKINGSESSIONDATE between  dateadd(MONTH, -12, current_date()) and CURRENT_DATE() 
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND CANSENDOFFERS = 'TRUE'
AND REGISTRATIONDATE BETWEEN  dateadd(MONTH, -12, current_date()) AND CURRENT_DATE()
UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND CANSENDOFFERS = 'TRUE'
AND REGISTRATIONDATE BETWEEN  dateadd(MONTH, -12, current_date()) AND CURRENT_DATE()
  )

SELECT DISTINCT CATEGORY FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS

--- TA VIC (active members, coaches, officials) ,   
-- TA SA (active members, coaches, officials).
-- TA NSW (active members, coaches, officials).
-- TA QLD (active members, coaches, officials).
-- TA ACT(active members, coaches, officials).
-- TA NT (active members, coaches, officials).
-- Hotshots (national ex WA) - active.
-- ATP/STC previous purchasers (last 3 years)
--fields-> email, state, country, source, MA, promocode.

SELECT EMAIL,
       STATE,
       COUNTRY,
       SOURCE,
        CASE WHEN STATE IN ('Tennis VIC','VIC','Tennis Victoria') AND SOURCE = 'MEMBER' THEN 'TennisVIC'
            WHEN STATE IN ('Tennis NSW','NSW') AND SOURCE = 'MEMBER' THEN 'TennisNSW'
            WHEN STATE IN ('Tennis QLD','Tennis Queensland','QLD') AND SOURCE = 'MEMBER' THEN 'TennisQLD'
            WHEN STATE IN ('Tennis SA','SA') AND SOURCE = 'MEMBER' THEN 'TennisSA'
            WHEN STATE IN ('Tennis ACT','ACT') AND SOURCE = 'MEMBER' THEN 'TennisACT'
            WHEN STATE IN ('Tennis NT','NT') AND SOURCE = 'MEMBER' THEN 'TennisNT'
            WHEN STATE IN ('Tennis Tasmania','TAS') AND SOURCE = 'MEMBER' THEN 'TennisTAS'
            WHEN SOURCE ='COACH' THEN 'Tennis22'
            WHEN SOURCE ='OFFICIAL' THEN 'Tennis22'
            WHEN SOURCE ='ANZHS' THEN 'HotShots22'
            WHEN SOURCE ='PURCHASER' THEN 'Thankyou22'            
        END AS PROMOCODE FROM
(SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND MA NOT IN ('Tennis West')
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
              AND MA NOT IN ('Tennis West')
              AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND S.NAME NOT IN ('WA')
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
               AND STATE NOT IN ('WA') 
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE HOMESTATE NOT IN ('WA') 
              AND EMAIL like '%@%'   
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND CANSENDOFFERS = TRUE
              AND STATE NOT IN ('WA')
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER' AS SOURCE, '5' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022','2021','2020') 
              AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
              AND CAN_CONTACT_EMAIL = TRUE
 ) A 
     )B
WHERE B.ROW_NUMBER = 1  
 
 
 select *   FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
--Merge query with priority

SELECT EMAIL,
       STATE,
       COUNTRY,
       SOURCE
FROM
(
  SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND MA NOT IN ('Tennis West')
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
              AND MA NOT IN ('Tennis West')
              AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND S.NAME NOT IN ('WA')
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
               AND STATE NOT IN ('WA') 
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE HOMESTATE NOT IN ('WA') 
              AND EMAIL like '%@%'   
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND CANSENDOFFERS = TRUE
              AND STATE NOT IN ('WA')
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER' AS SOURCE, '5' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022','2021','2020') 
              AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
              AND CAN_CONTACT_EMAIL = TRUE
 ) A
)B
WHERE B.ROW_NUMBER = 1  

--AO22 PX ticket purchasers
SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND BOOKING_SOURCE ='ARCHTICS'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
--2336

SELECT * FROM "PROD_LANDING_DB"."SHOPIFY"."MERCHANDISE_SALE"

---Active and opted in:
--1. Members (NSW, QLD, ACT)
--2. Coaches (NSW, QLD, ACT)
--3. Officials (NSW, QLD, ACT)
--4. Hot Shots (NSW, QLD, ACT)
--5. ATP/STC prev purchasers (NSW, QLD, ACT) (22, 21, 20, 19)
--6. Davis Cup prev purchasers (all states, excl. WA) (21, 20, 19)
--fields 1. Email
--2. Source
--3. State
--4. Country
           
               
SELECT EMAIL,
       STATE,
       COUNTRY,
       SOURCE
       
FROM
(
  SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND MA IN ('Tennis NSW','Tennis Queensland','Tennis ACT')
               AND CANSENDOFFERS = TRUE
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
              AND MA IN ('Tennis NSW','Tennis Queensland','Tennis ACT')
              AND CANSENDOFFERS = TRUE
              AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND S.NAME IN ('NSW','QLD','ACT')
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
               AND STATE IN ('NSW','QLD','ACT')
               AND CANSENDOFFERS = TRUE
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE HOMESTATE IN ('NSW','QLD','ACT') 
              AND EMAIL like '%@%'  
               AND CANSENDOFFERS = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND CANSENDOFFERS = TRUE
              AND STATE IN ('NSW','QLD','ACT') 
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_STC_ATP' AS SOURCE, '5' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022','2021','2020','2019') 
              AND STATE IN ('NSW','QLD','ACT')
              AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
              AND CAN_CONTACT_EMAIL = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_DAVIS' AS SOURCE, '6' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020','2019') 
              AND STATE NOT IN ('WA')
              AND EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
              AND CAN_CONTACT_EMAIL = TRUE 
 ) A
)B
WHERE B.ROW_NUMBER = 1  


--All Davis Cup 2022 purchasers
--(ok to include opt-outs)
--email

SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
AND EMAIL_ADDRESS LIKE '%@%'     




select distinct EVENT_TOURNAMENT_SERIES_YEAR, EVENT_TOURNAMENT_NAME
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')

--All opted in
---Court hire bookers - 3 years
--Cardio tennis bookers - 3 years
--ANZ Hot Shots - 3 years
--Remove:
--Court hire bookers - 12 months
--Cardio tennis bookers - 12 months
--ANZ Hot Shots - 12 months

select distinct state from
(SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY             
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE USER_CANSENDOFFERS ='Yes'
AND BOOKINGSESSIONDATE BETWEEN DATEADD(YEAR, -3, CURRENT_DATE()) AND DATEADD(YEAR, -1, CURRENT_DATE())
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND CANSENDOFFERS = 'TRUE'
AND REGISTRATIONDATE BETWEEN DATEADD(YEAR, -3, CURRENT_DATE()) AND DATEADD(YEAR, -1, CURRENT_DATE())
UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND CANSENDOFFERS = 'TRUE'
AND REGISTRATIONDATE BETWEEN DATEADD(YEAR, -3, CURRENT_DATE()) AND DATEADD(YEAR, -1, CURRENT_DATE())
  ) A
  )B
WHERE B.ROW_NUMBER = 1 
 )

------AO PX Purchasers
--2336 TOTAL

SELECT * FROM "DEV_LANDING_DB"."PUBLIC"."PX_PURCHASES"

SELECT * FROM "DEV_LANDING_DB"."PUBLIC"."PX_PURCHASES"
WHERE CODE NOT IN ('E1',
'E49',
'E48',
'E2049',
'E2055',
'E1685',
'E329',
'E1455',
'E907',
'E1519',
'E2367',
'E758',
'E2312',
'E890',
'E706',
'E2208',
'E2233',
'E1847',
'E817',
'E1130',
'E275',
'E2305',
'E638',
'E1410',
'E1629',
'E62',
'E2193',
'E1437',
'E444',
'E1501',
'E1665',
'E2161',
'E91',
'E1255',
'E381',
'E546',
'E1069',
'E1934',
'E2231',
'E1804',
'E901',
'E1260',
'E1139',
'E843',
'E1184',
'E1052',
'E152',
'E211',
'E356',
'E419',
'E1324',
'E72',
'E959',
'E1987',
'E2183',
'E2341',
'E1420',
'E423',
'E565',
'E1461',
'E982',
'E1721',
'E2040',
'E1811',
'E459',
'E1086',
'E1173',
'E118',
'E2296',
'E545',
'E1702',
'E1899',
'E336',
'E2381',
'E383',
'E189',
'E861',
'E1159',
'E1979',
'E1885',
'E782',
'E809',
'E2043',
'E779',
'E854',
'E1198',
'E2012',
'E2005',
'E637',
'E1475',
'E390',
'E875',
'E276',
'E1603',
'E2206',
'E514',
'E127',
'E891',
'E1021',
'E549',
'E543',
'E558',
'E1239',
'E820',
'E2168',
'E257',
'E1330',
'E2034',
'E1924',
'E1756',
'E102',
'E1625',
'E238',
'E204',
'E2136',
'E377',
'E1378',
'E527',
'E2363',
'E555',
'E504',
'E1634',
'E2070',
'E899',
'E120',
'E1371',
'E924',
'E639',
'E1332',
'E385',
'E1343',
'E1070',
'E564',
'E2196',
'E248',
'E1656',
'E1145',
'E520',
'E486',
'E2192',
'E1703',
'E1872',
'E984',
'E1611',
'E224',
'E702',
'E1562',
'E522',
'E2375',
'E107',
'E2351',
'E405',
'E131',
'E310',
'E271',
'E508',
'E1180',
'E439',
'E1322',
'E2165',
'E1151',
'E659',
'E1009',
'E1174',
'E1748',
'E1914',
'E1435',
'E1140',
'E187',
'E1196',
'E1207',
'E523',
'E2243',
'E80',
'E2162',
'E145',
'E487',
'E1922',
'E2292',
'E1209',
'E1358',
'E282',
'E1444',
'E143',
'E1147',
'E1273',
'E1006',
'E811',
'E1008',
'E374',
'E1141',
'E993',
'E432',
'E1839',
'E2099',
'E1247',
'E2230',
'E141',
'E2053',
'E726',
'E911',
'E411',
'E1869',
'E835',
'E132',
'E2239',
'E1732',
'E615',
'E283',
'E2280',
'E1925',
'E1659',
'E934',
'E240',
'E314',
'E2362',
'E1311',
'E2018',
'E177',
'E2248',
'E2364',
'E1351',
'E582',
'E1708',
'E2044',
'E2207',
'E1789',
'E65',
'E592',
'E792',
'E990',
'E2365',
'E1546',
'E155',
'E2109',
'E985',
'E938',
'E1416',
'E894',
'E207',
'E2327',
'E1072',
'E1712',
'E1772',
'E663',
'E210',
'E2335',
'E650',
'E510',
'E2304',
'E1696',
'E1127',
'E1306',
'E805',
'E1107',
'E1734',
'E1319',
'E1663',
'E1049',
'E1710',
'E1066',
'E1419',
'E771',
'E1750',
'E382',
'E1767',
'E2241',
'E1812',
'E1860',
'E1933',
'E163',
'E2337',
'E1689',
'E1450',
'E1441',
'E1123',
'E1583',
'E1840',
'E632',
'E2295',
'E1990',
'E1642',
'E2030',
'E1723',
'E287'
)

--------Grace period of 12 months if not active (active now or active in past 12 months):
--1. Members (NSW, QLD, ACT)
--2. Coaches  (NSW, QLD, ACT)
--3. Officials  (NSW, QLD, ACT)
--4. Hot Shots  (NSW, QLD, ACT)
--5. Previous Davis Cup purchasers (2021, 2020, 2019)
--6. Previous ATP Cup and STC purchasers (2021, 2020, 2019) - only NSW, QLD and ACT

SELECT * FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
WHERE TACURRENT12MONTH = 'Y'

SELECT EMAIL
      STATE,
       COUNTRY,
      SOURCE
       
FROM
(
  SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND MA IN ('Tennis NSW','Tennis Queensland','Tennis ACT')
              AND CANSENDOFFERS = TRUE
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
              AND MA IN ('Tennis NSW','Tennis Queensland','Tennis ACT')
              AND CANSENDOFFERS = TRUE
              AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND S.NAME IN ('NSW','QLD','ACT')
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
               AND STATE IN ('NSW','QLD','ACT')
             AND CANSENDOFFERS = TRUE
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE HOMESTATE IN ('NSW','QLD','ACT') 
              AND EMAIL like '%@%'  
              AND CANSENDOFFERS = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND CANSENDOFFERS = TRUE
              AND STATE IN ('NSW','QLD','ACT') 
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_STC_ATP' AS SOURCE, '5' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020','2019') 
              AND STATE IN ('NSW','QLD','ACT')
              AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
            AND CAN_CONTACT_EMAIL = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_DAVIS' AS SOURCE, '6' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020','2019') 
              --AND STATE NOT IN ('WA')
              AND EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
             AND CAN_CONTACT_EMAIL = TRUE 
 ) A
)B
WHERE B.ROW_NUMBER = 1  

--Exclusion list Previous Davis Cup purchasers (2021, 2020, 2019)
  SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL-- ,STATE, COUNTRY, 'PURCHASER_DAVIS' AS SOURCE, '6' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR ='2022'--IN ('2021','2020','2019') 
              --AND STATE NOT IN ('WA')
              AND EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
           --  AND CAN_CONTACT_EMAIL = TRUE 

--New participants for court hire

SELECT SUM(NEWCHPARTICANPTS) FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE"

WHERE DATE LIKE '%2022-02%'

--1. Davis Cup 2022 purchasers (opt in and opt outs)
SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
AND EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EMAIL_ADDRESS LIKE '%@%'  


----ALL AO 2022 PURCHASES OPTIN
SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
--74544


----ALL AO 2021 PURCHASES OPTIN
SELECT COUNT (EMAIL) FROM
(SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2021'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
AND DATA_SOURCE ='Ticketmaster') --25577

----ALL AO 2020 PURCHASES OPTIN
SELECT COUNT (EMAIL) FROM
(SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2020'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
AND DATA_SOURCE ='Ticketmaster') --108731

----ALL AO 2019 PURCHASES OPTIN
SELECT DISTINCT DATA_SOURCE FROM
(SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY, DATA_SOURCE
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2019'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE)
--AND DATA_SOURCE ='Ticketmaster') --83531


--All opted in
--Court hire bookers - 2 Feb 21 to 2 Feb 22
--Cardio tennis bookers - 2 Feb 21 to 2 Feb 22
--ANZ Hot Shots - 2 Feb 21 to 2 Feb 22
--union
--exclusion
--Court hire bookers - 3 Feb 22 onwards
--Cardio tennis bookers - 3 Feb 22 onwards
--ANZ Hot Shots - 3 Feb 22 onwards

select top 1 *  FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"

SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY             
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-02-02'AND '2022-02-02'
AND USER_CANSENDOFFERS ='Yes'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-02-02' AND '2022-02-02'
AND CANSENDOFFERS = 'TRUE'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-02-02' AND '2022-02-02'
AND CANSENDOFFERS = 'TRUE'
  ) A
  )B
WHERE B.ROW_NUMBER = 1 
UNION
SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY             
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE >= '2022-02-03'
    UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-02-03'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-02-03'
  ) A
  )B
WHERE B.ROW_NUMBER = 1 
 
 
 -----------------------------------------
 
 SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY             
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-02-25'AND '2022-02-02'
AND USER_CANSENDOFFERS ='Yes'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-02-25' AND '2022-02-02'
AND CANSENDOFFERS = 'TRUE'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-02-25' AND '2022-02-02'
AND CANSENDOFFERS = 'TRUE'
  UNION
  SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '4' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE >= '2022-02-03'
    UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '5' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-02-03'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '6' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-02-03'
  ) A
  )B
WHERE B.ROW_NUMBER = 1 

--------------------------1 Mar 22

--Grace period of 12 months if not active (active now or active in past 12 months):
--1. Members (NSW & ACT)
--2. Coaches  (NSW & ACT)
--3. Officials  (NSW & ACT)
--4. Hot Shots  (NSW & ACT)
--5. Previous Davis Cup purchasers (2021, 2020, 2019)
--6. Previous ATP Cup and STC purchasers (2021, 2020, 2019) - only NSW & ACT



SELECT * FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
WHERE TACURRENT12MONTH = 'Y'

SELECT EMAIL,
      STATE,
      COUNTRY,
      SOURCE
       
FROM
(
  SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND MA IN ('Tennis NSW','Tennis ACT')
              AND CANSENDOFFERS = TRUE
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
              AND MA IN ('Tennis NSW','Tennis ACT')
              AND CANSENDOFFERS = TRUE
              AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND S.NAME IN ('NSW','ACT')
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
               AND STATE IN ('NSW','ACT')
             AND CANSENDOFFERS = TRUE
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE HOMESTATE IN ('NSW','ACT') 
              AND EMAIL like '%@%'  
              AND CANSENDOFFERS = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND CANSENDOFFERS = TRUE
              AND STATE IN ('NSW','ACT') 
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_STC_ATP' AS SOURCE, '5' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020','2019') 
              AND STATE IN ('NSW','ACT')
              AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
            AND CAN_CONTACT_EMAIL = TRUE
                     UNION
               SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'PURCHASER_DAVIS' AS SOURCE, '6' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020','2019') 
              --AND STATE NOT IN ('WA')
              AND EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
             AND CAN_CONTACT_EMAIL = TRUE 
 ) A
)B
WHERE B.ROW_NUMBER = 1  

--Exclusion list Previous Davis Cup purchasers (2021, 2020, 2019)
  SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL-- ,STATE, COUNTRY, 'PURCHASER_DAVIS' AS SOURCE, '6' AS PRIORITY 
              FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE  EVENT_TOURNAMENT_SERIES_YEAR ='2022'--IN ('2021','2020','2019') 
              --AND STATE NOT IN ('WA')
              AND EVENT_TOURNAMENT_NAME IN ('DAVIS CUP')
              AND EMAIL_ADDRESS LIKE '%@%'     
           --  AND CAN_CONTACT_EMAIL = TRUE 

--Dev 1934

-----------------------

--Grace period of 12 months if not active (active now or active within last 12 months)

--All states unless otherwise stated.

--1. Members
--2. Coaches
--3. Officials
--4. Hot Shots
--5. Previous Billie Jean King Cup/Fed Cup purchasers (2019) -- 'BILLIE JEAN KING CUP' ,'FED CUP'
--6. Previous Brisbane International purchasers (2020) --'BRISBANE INTERNATIONAL'
--7. Previous Brisbane ATP Cup purchasers (2020) --ATP CUP
--8. AO22 purchasers (Queensland only) --AUSTRALIAN OPEN

SELECT EMAIL,
       STATE,
       COUNTRY,
       SOURCE,
        CASE WHEN STATE IN ('Tennis VIC','VIC','Tennis Victoria') AND SOURCE = 'MEMBER' THEN 'TennisVIC'
            WHEN STATE IN ('Tennis NSW','NSW') AND SOURCE = 'MEMBER' THEN 'TennisNSW'
            WHEN STATE IN ('Tennis QLD','Tennis Queensland','QLD') AND SOURCE = 'MEMBER' THEN 'TennisQLD'
            WHEN STATE IN ('Tennis SA','SA') AND SOURCE = 'MEMBER' THEN 'TennisSA'
            WHEN STATE IN ('Tennis ACT','ACT') AND SOURCE = 'MEMBER' THEN 'TennisACT'
            WHEN STATE IN ('Tennis NT','NT') AND SOURCE = 'MEMBER' THEN 'TennisNT'
            WHEN STATE IN ('Tennis Tasmania','TAS') AND SOURCE = 'MEMBER' THEN 'TennisTAS'
            WHEN SOURCE ='COACH' THEN 'Tennis22'
            WHEN SOURCE ='OFFICIAL' THEN 'Tennis22'
            WHEN SOURCE ='ANZHS' THEN 'HotShots22'
            WHEN SOURCE ='BILLIE JEAN KING/FED CUP PURCHASER' THEN 'Thankyou22'  
            WHEN SOURCE ='BRISBANE INTERNATIONAL PURCHASER' THEN 'Thankyou22'
            WHEN SOURCE ='BRISBANE ATP CUP PURCHASER' THEN 'Thankyou22'
            WHEN SOURCE ='AO 22 PURCHASER' THEN 'Thankyou22'
            WHEN SOURCE ='DAVIS CUP 22 PURCHASER' THEN 'Thankyou22' 
        END AS PROMOCODE FROM
(SELECT  A.EMAIL,A.STATE,A.COUNTRY,A.SOURCE,ROW_NUMBER() 
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
         FROM
              (SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE, COUNTRY,'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_MT2_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND EMAIL like '%@%'
                       UNION 
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MA AS STATE,COUNTRY,'MEMBER' AS SOURCE ,'1' AS PRIORITY
               FROM PROD_WAREHOUSE_DB.DWH.VW_CS_PARTICIPANTS_90DAY_12MTHCURRENT
               WHERE TACURRENT12MONTH = 'Y'
               AND EMAIL like '%@%'
                       UNION
               SELECT DISTINCT LOWER(PROD_STAGING_DB.CHEETAHMAIL.return_valid_email(A.EMAILADDRESS)) AS EMAIL,S.NAME AS STATE,C.NAME AS COUNTRY, 'MEMBER' AS SOURCE,'1' AS PRIORITY
               FROM  PROD_STAGING_DB.MT2.KEY_CONTACT A
               left JOIN PROD_STAGING_DB.MT2.ENTITY_PROFILE_ADDRESS P ON A.ENTITYPROFILEID = P.ENTITYPROFILEID 
               left JOIN PROD_STAGING_DB.MT2.STATE S ON P.STATEID = S.STATEID
               left JOIN PROD_STAGING_DB.MT2.COUNTRY C ON P.COUNTRYID = C.COUNTRYID
               WHERE A.EMAILADDRESS like '%@%'
               AND A.ISCURRENT = TRUE            
                      UNION 
               SELECT DISTINCT LOWER(COACHEMAIL) AS EMAIL,STATE,COUNTRY,'COACH' AS SOURCE, '2' AS PRIORITY
               FROM PROD_STAGING_DB.MT1.V_RPT_ALL_COACHES  
               WHERE COALESCE(to_date(CMR_ENDDATE), CM_ENDDATE)  >=  current_date()  
               AND COACHEMAIL LIKE '%@%'
                      UNION
              SELECT DISTINCT LOWER(EMAIL) AS EMAIL,HOMESTATE AS STATE, HOMECOUNTRY AS COUNTRY,'OFFICIAL' AS SOURCE,'3' AS PRIORITY
              FROM  PROD_WAREHOUSE_DB.DWH.RPT_CURRENT_OFFICIALS
              WHERE EMAIL like '%@%'   
                     UNION
               SELECT DISTINCT LOWER(EMAIL) AS EMAIL,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY,'ANZHS' AS SOURCE,'4' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
              WHERE CATEGORY = 'TENNIS HOT SHOTS PARTICIPANT'
              AND FINANCIALYEAR IN ('21-22','20-21','19-20')
              AND EMAIL like '%@%'
                       UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'BILLIE JEAN KING/FED CUP PURCHASER' AS SOURCE, '5' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2019'
              AND EVENT_TOURNAMENT_NAME IN ('BILLIE JEAN KING CUP','FED CUP')
              AND EMAIL_ADDRESS LIKE '%@%'
               AND CAN_CONTACT_EMAIL = TRUE
               UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'BRISBANE INTERNATIONAL PURCHASER' AS SOURCE, '6' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2020'
              AND EVENT_TOURNAMENT_NAME = 'BRISBANE INTERNATIONAL'
              AND EMAIL_ADDRESS LIKE '%@%'  
              AND CAN_CONTACT_EMAIL = TRUE
               UNION
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'BRISBANE ATP CUP PURCHASER' AS SOURCE, '7' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2020'
              AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
              AND STATE ='QLD'
              AND EVENT_VENUE IN ('QUEENSLAND TENNIS CENTRE', 'PAT RAFTER ARENA')
              AND EMAIL_ADDRESS LIKE '%@%'   
              AND CAN_CONTACT_EMAIL = TRUE
               UNION 
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'AO 22 PURCHASER' AS SOURCE, '8' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
              AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
              AND STATE ='QLD'
              AND EMAIL_ADDRESS LIKE '%@%'
              AND CAN_CONTACT_EMAIL = TRUE
                UNION 
              SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL ,STATE, COUNTRY, 'DAVIS CUP 22 PURCHASER' AS SOURCE, '9' AS PRIORITY 
              FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
              WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
              AND EVENT_TOURNAMENT_NAME = 'DAVIS CUP'
              AND EMAIL_ADDRESS LIKE '%@%'
              AND CAN_CONTACT_EMAIL = TRUE
                ) A 
     )B
WHERE B.ROW_NUMBER = 1  

SELECT distinct EVENT_VENUE  --DISTINCT EVENT_TOURNAMENT_NAME
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_NAME ='ATP CUP'
and EVENT_TOURNAMENT_SERIES_YEAR ='2020'
and state ='QLD' --QUEENSLAND TENNIS CENTRE, PAT RAFTER ARENA
ORDER BY EVENT_TOURNAMENT_NAME

---1. Previous AO purchasers (2021, 2020)
--2. Previous ATP Cup & STC purchasers (2022, 2021, 2020)

--PLEASE ALSO NOTE THE SEPARATE EXCLUSION LIST OF BJKC 2022 PURCHASERS

SELECT EMAIL, SOURCE, STATE,COUNTRY
FROM
(
SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY, '1' AS PRIORITY 
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_SERIES_YEAR IN ('2021','2020')
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE
UNION
SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL,'PURCHASER_STC_ATP' AS SOURCE, STATE, COUNTRY,'2' AS PRIORITY 
FROM  PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE  EVENT_TOURNAMENT_SERIES_YEAR IN ('2022','2021','2020') 
AND EVENT_TOURNAMENT_NAME IN ('SYDNEY TENNIS CLASSIC','ATP CUP')
AND EMAIL_ADDRESS LIKE '%@%'     
AND CAN_CONTACT_EMAIL = TRUE)


---BJKC 2022 Exclusion List
SELECT DISTINCT LOWER(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'BILLIE JEAN KING CUP'
AND EMAIL_ADDRESS like '%@%'


-----AO 22 Purchasers

SELECT distinct lower(EMAIL_ADDRESS) AS EMAIL, 'AO' AS SOURCE, STATE, COUNTRY
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
where EVENT_TOURNAMENT_SERIES_YEAR = '2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND EMAIL_ADDRESS like '%@%'
AND CAN_CONTACT_EMAIL = TRUE

--All opted in:
--Court hire bookers - 12 months
--Cardio tennis bookers - 12 months
--ANZ Hot Shots - 12 months
--Remove:Court Hire, Cardio Tennis and Hot Shots bookings from 15/03/2022 and future bookings.


SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY           
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY, ROW_NUMBER()
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-03-15'AND '2022-03-14'
AND USER_CANSENDOFFERS ='Yes'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY 
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-03-15'AND '2022-03-14'
AND CANSENDOFFERS = 'TRUE'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-03-15'AND '2022-03-14'
AND CANSENDOFFERS = 'TRUE'
  ) A
  )B
WHERE B.ROW_NUMBER = 1 
AND SOURCE = 'ANZ HS'
AND STATE ='INTL'


SELECT * --DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE BETWEEN '2021-03-15'AND '2022-03-14'
AND CANSENDOFFERS = 'TRUE'
AND STATE ='INTL'

---Exclusion list for Court Hire, Cardio Tennis and Hot Shots bookings from 15/03/2022 and future bookings

SELECT DISTINCT EMAIL,
       SOURCE,
       STATE,
       COUNTRY
       
FROM
(
SELECT  A.EMAIL,A.SOURCE,A.STATE,A.COUNTRY, ROW_NUMBER()
         OVER (PARTITION BY EMAIL ORDER BY PRIORITY) AS ROW_NUMBER
FROM
(
SELECT DISTINCT(LOWER(CONTACT_EMAILADDRESS)) AS EMAIL, 'CHBOOKINGS' AS SOURCE,  STATE, CONTACT_COUNTRY AS COUNTRY, '1' AS PRIORITY 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE >= '2022-03-15'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'CARDIO' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '2' AS PRIORITY 
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='CARDIO TENNIS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-03-15'
  UNION
SELECT DISTINCT(LOWER(EMAIL)) AS EMAIL, 'ANZ HS' AS SOURCE,MAILSTATE AS STATE, MAILCNTRY AS COUNTRY, '3' AS PRIORITY
FROM PROD_WAREHOUSE_DB.DWH.RPT_CARDIO_HOTSHOT_PARTICIPANTS
WHERE CATEGORY ='TENNIS HOT SHOTS PARTICIPANT'
AND REGISTRATIONDATE >= '2022-03-15'
  ) A
  )B
WHERE B.ROW_NUMBER = 1 



















