----************************Patron Location Data-NSW**************

--*********************ATP CUP**************************** ATP CUP
--TOTAL

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
--50883

--1. Local
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--40098, 40063


--INTERSTATE
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND STATE <>'NSW'
AND POSTCODE NOT IN (SELECT * FROM SYDNEY)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--1083

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--191

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND (POSTCODE IS NULL
    OR POSTCODE =''
    OR COUNTRY IS NULL
    OR COUNTRY =''
     )
     ORDER BY POSTCODE
--10363 

------Intrastate

---City of Sydney 

SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE BETWEEN '2000' AND '2001'
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--432

--Greater Metro 
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
             WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM SYDNEY )
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--17678

--Regional NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--22194

--------State Breakdown
--ACT
WITH ACT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0200' AND '0299' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2600' AND '2618' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2900' AND '2920' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM ACT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--336

--NSW
WITH NSW AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM NSW)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--40175

--NT
WITH NT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0800' AND '0899' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '0900' AND '0999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM NT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--10

--QLD
WITH QLD AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '4000' AND '4999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '9000' AND '9999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM QLD)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--259

--SA
WITH SA AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '5000' AND '5799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '5800' AND '5999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM SA)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--25

--TAS
WITH TAS AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '7000' AND '7799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '7800' AND '7999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM TAS)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--34

--VIC
WITH VIC AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND POSTCODE IN (SELECT * FROM VIC)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--735


----****************************************************************STC CUP**************************** SYDNEY TENNIS CLASSIC


--1. Local
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--40098, 40063


--INTERSTATE
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND STATE <>'NSW'
AND POSTCODE NOT IN (SELECT * FROM SYDNEY)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--1083

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--191

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND (POSTCODE IS NULL
    OR POSTCODE =''
    OR COUNTRY IS NULL
    OR COUNTRY =''
     )
     ORDER BY POSTCODE
--10363 

------Intrastate

---City of Sydney 

SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE BETWEEN '2000' AND '2001'
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--432

--Greater Metro 
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
             WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
             WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SYDNEY )
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--17678

--Regional NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--22194

--------State Breakdown
--ACT
WITH ACT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0200' AND '0299' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2600' AND '2618' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2900' AND '2920' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM ACT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--336

--NSW
WITH NSW AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM NSW)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--40175

--NT
WITH NT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0800' AND '0899' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '0900' AND '0999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM NT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--10

--QLD
WITH QLD AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '4000' AND '4999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '9000' AND '9999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM QLD)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--259

--SA
WITH SA AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '5000' AND '5799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '5800' AND '5999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SA)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--25

--TAS
WITH TAS AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '7000' AND '7799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '7800' AND '7999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM TAS)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--34

--VIC
WITH VIC AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM VIC)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--735

SELECT count (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'

SELECT  DISTINCT SALE_TRANSACTION_TYPE
FROM "PROD_WAREHOUSE_DB"."DWH"."FACT_TICKETMASTER"
WHERE EVENT_TOURNAMENT_NAME_YEAR ='AUSTRALIAN OPEN 2022'

SELECT * --DISTINCT FANTM_EVENT_NAME
FROM "PROD_WAREHOUSE_DB"."DWH"."FACT_TICKETMASTER_ATTENDANCE" a
LEFT JOIN FACT_TICKETMASTER_EVENT B
ON A.FANTM_EVENT_NAME = B.FANTM_EVENT_NAME
WHERE B.SEASON_NAME LIKE '%AO%'
AND SEASON_YEAR ='2022'
ORDER BY FANTM_EVENT_NAME
        
        
SELECT * FROM FACT_TICKETMASTER_EVENT