--************************************Patron Location Data-VIC********************

--******************** AO **************************** AUSTRALIAN OPEN
--TOTAL

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
--560892

--1. Local
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--303369


--INTERSTATE
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND STATE <>'VIC'
AND POSTCODE NOT IN (SELECT * FROM MEL)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--108201

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--6642

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND (POSTCODE IS NULL
    OR POSTCODE =''
       OR COUNTRY IS NULL
   OR COUNTRY =''
     )
     ORDER BY POSTCODE
--254475

------Intrastate

---City of Melbourne 
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8001' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--22341

--Greater Metro 
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3002' AND '3207' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8002' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM MEL )
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--249055

--Regional VIC
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3208' AND '3999' THEN POSTCODE
                END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--54314

--------State Breakdown
--ACT
WITH ACT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0200' AND '0299' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2600' AND '2618' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2900' AND '2920' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM ACT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--4796

--NSW
WITH NSW AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM NSW)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--73256

--NT
WITH NT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0800' AND '0899' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '0900' AND '0999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM NT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--299

--QLD
WITH QLD AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '4000' AND '4999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '9000' AND '9999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM QLD)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--17531

--SA
WITH SA AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '5000' AND '5799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '5800' AND '5999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM SA)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--4770

--TAS
WITH TAS AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '7000' AND '7799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '7800' AND '7999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM TAS)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--2613

--VIC
WITH VIC AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND POSTCODE IN (SELECT * FROM VIC)
AND STATE = 'VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--305263

--******************** MSS **************************** MELBOURNE SUMMER SERIES

--1. Local
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--303369


--INTERSTATE
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
             END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND STATE <>'VIC'
AND POSTCODE NOT IN (SELECT * FROM MEL)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--108201

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--6642

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND (POSTCODE IS NULL
    OR POSTCODE =''
       OR COUNTRY IS NULL
   OR COUNTRY =''
     )
     ORDER BY POSTCODE
--254475

------Intrastate

---City of Melbourne 
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8001' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--22341

--Greater Metro 
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3002' AND '3207' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8002' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM MEL )
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--249055

--Regional VIC
WITH MEL AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3208' AND '3999' THEN POSTCODE
                END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM MEL)
AND STATE ='VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--54314

--------State Breakdown
--ACT
WITH ACT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0200' AND '0299' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2600' AND '2618' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2900' AND '2920' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM ACT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--4796

--NSW
WITH NSW AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM NSW)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--73256

--NT
WITH NT AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '0800' AND '0899' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '0900' AND '0999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM NT)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--299

--QLD
WITH QLD AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '4000' AND '4999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '9000' AND '9999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM QLD)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--17531

--SA
WITH SA AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '5000' AND '5799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '5800' AND '5999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM SA)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--4770

--TAS
WITH TAS AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '7000' AND '7799' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '7800' AND '7999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM TAS)
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--2613

--VIC
WITH VIC AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
(SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '3000' AND '3999' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '8000' AND '8999' THEN POSTCODE
                 END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND POSTCODE IN (SELECT * FROM VIC)
AND STATE = 'VIC'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--305263

SELECT COUNT(*)
FROM "PROD_WAREHOUSE_DB"."DWH"."FACT_TICKETING"
WHERE EVENT_TOURNAMENT_NAME_YEAR = 'AUSTRALIAN OPEN 2022'
AND PRICE_CATEGORY_NAME IN ('A', 'B', 'G', 'J', 'K', 'L', 'M', 'N', 'Ground Pass', 'T' )
AND PRICE_TYPE_NAME NOT IN ('Carpark', 'NA', 'Beach House Weekenders', 'AO 2022 Comfort Pack', 'AO 2022 Player Towel')
;

SELECT DISTINCT DATA_SOURCE --TOP 10 * 
FROM "PROD_WAREHOUSE_DB"."DWH"."FACT_TICKETING"

SELECT COUNT (DISTINCT SEQ_ID) --,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) --,POSTCODE, STATE, COUNTRY)
FROM PROD_WAREHOUSE_DB.DWH.REPORTING_TICKETING
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND PRICE_CATEGORY_NAME IN ('A', 'B', 'G', 'J', 'K', 'L', 'M', 'N', 'Ground Pass', 'T' )
AND PRICE_TYPE_NAME NOT IN ('Carpark', 'NA', 'Beach House Weekenders', 'AO 2022 Comfort Pack', 'AO 2022 Player Towel')
--3,46,468
--3,65,942