---**********************************Digital participation***************

----OCS TRANSACTIONS - USING CREATED DATE
WITH OCS AS (
select STATE,ORGANISATION_NAME,to_varchar(ORGANISATION_MODIFIEDDATETIME,'MON-YY') as MONTH,count(*) COUNT --ORGANISATION_CREATEDDATETIME, ORGANISATION_MODIFIEDDATETIME
from "PROD_WAREHOUSE_DB"."DWH"."VW_OCS_SESSION_REGISTRATIONS"
where cast(ORGANISATION_MODIFIEDDATETIME as date) >= '2020-10-01'
 -- AND ORGANISATIONTYPE_NAME ='Venue'
group by STATE,ORGANISATION_NAME,MONTH
)
select *
from OCS
pivot(MAX(COUNT) for MONTH in ('Jan-22','Dec-21','Nov-21','Oct-21','Sep-21','Aug-21','Jul-21','Jun-21','May-21','Apr-21','Mar-21','Feb-21','Jan-21','Dec-20','Nov-20','Oct-20'))
as p (STATE,ORGANISATION_NAME,Jan_22,Dec_21,Nov_21,Oct_21,Sep_21,Aug_21,Jul_21,Jun_21,May_21,Apr_21,Mar_21,Feb_21,Jan_21,Dec_20,Nov_20,Oct_20)
order by STATE,ORGANISATION_NAME

SELECT DISTINCT STATE,ORGANISATION_NAME,ORGANISATION_CREATEDDATETIME 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_OCS_SESSION_REGISTRATIONS"
ORDER BY ORGANISATION_CREATEDDATETIME DESC
WHERE ORGANISATION_CREATEDDATETIME >= '2020-10-01'--Venue

SELECT * --SUM(NEWCHPARTICANPTS) 
FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE"
WHERE DATE ='2022-01-31'

SELECT SUM(NEWCHPARTICANPTS)  FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE_WEEKLY"
WHERE DATE LIKE '%2022-01%'


-----------------------Participation Bookers

--Court Hire Bookings

SELECT  COUNT (DISTINCT BOOKINGSESSION_ID) 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE LIKE '%2022-02%' 
--75432, Matching with Campaign performance court hire bookings

--Court Hire Players/ Bookers

SELECT  COUNT (DISTINCT CONTACT_ID) 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE LIKE '%2022-02%' 
--30361, Matching with Campaign performance court hire players

SELECT TOP 10 * -- DISTINCT BOOKINGSESSIONCATEGORY_NAME --TOP 10 * 
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"


--Court Hire Players/ Bookers State wise split

SELECT  COUNT (DISTINCT CONTACT_ID) , STATE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE LIKE '%2022-02%' 
GROUP BY STATE

---------------------------------New Bookers (Emails with a particular month booking date, no other record than that month)------------------------------
--JAN21
SELECT COUNT (*) AS JAN21 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-01-01' AND '2021-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2021-01-01'
)) --5467

--FEB21
SELECT COUNT (*) AS FEB21 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-02-01' AND '2021-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2021-02-01'
))


------------------------------------------------------------------------
--JAN22
SELECT COUNT (*) AS JAN22 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2022-01-01' AND '2022-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2022-01-01'
))

--FEB22
SELECT COUNT (*) AS FEB22 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2022-02-01' AND '2022-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2022-02-01'
))

---------------------------------New Bookers (Emails with booking date current month - last 6 months, no other record than that )-----------------------------

--JAN21
SELECT COUNT (*) AS JAN21 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-08-01' AND '2021-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-08-01'
)) 

--FEB21
SELECT COUNT (*) AS FEB21 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-09-01' AND '2021-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-09-01'
))


------------------------------------------------------------------------
--JAN22
SELECT COUNT (*) AS JAN22 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-08-01' AND '2022-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2021-08-01'
))

--FEB22
SELECT COUNT (*) AS FEB22 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2021-09-01' AND '2022-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2021-09-01'
))



SELECT * FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE CONTACT_EMAILADDRESS ='kristie.tannock@gmail.com'

---------------------------------New Bookers (Emails with booking date current month - last 18 months, no other record than that )-----------------------------

--JAN21
SELECT COUNT (*) AS JAN21 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2019-08-01' AND '2021-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2019-08-01'
)) 

--FEB21
SELECT COUNT (*) AS FEB21 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2019-09-01' AND '2021-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2019-09-01'
))


------------------------------------------------------------------------
--JAN22
SELECT COUNT (*) AS JAN22 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-08-01' AND '2022-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-08-01'
))

--FEB22
SELECT COUNT (*) AS FEB22 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-09-01' AND '2022-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-09-01'
))


---------------------------------New Bookers (Emails with booking date current month - last 2 Years, no other record than that )-----------------------------
--JAN21
SELECT COUNT (*) AS JAN21 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2019-02-01' AND '2021-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2019-02-01'
)) 

--FEB21
SELECT COUNT (*) AS FEB21 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2019-03-01' AND '2021-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2019-03-01'
))


------------------------------------------------------------------------
--JAN22
SELECT COUNT (*) AS JAN22 FROM
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-02-01' AND '2022-01-31'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-02-01'
))

--FEB22
SELECT COUNT (*) AS FEB22 FROM
(SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE BETWEEN '2020-03-01' AND '2022-02-28'
EXCEPT
(
SELECT DISTINCT LOWER(CONTACT_EMAILADDRESS) AS EMAIL--, CONTACT_FIRSTNAME,CONTACT_LASTNAME,USER_BIRTHDATE,USER_GENDER,CONTACT_PHONENUMBER,USER_POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE < '2020-03-01'
))

----------------------------------------------------------------------

SELECT sum (NEWCHPARTICANPTS)
FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE"
WHERE DATE like '%2022-01%'
group by state

SELECT sum (NEWCHPARTICANPTS) 
FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE_WEEKLY"
WHERE DATE LIKE '%2022-01%'

7 jan: all emails from 1 Jan 22 to 7 Jan 22, and not in 1 Jan 20 to 31 Dec 21
14 Jan: all emails from 7 Jan to 14 Jan, and not in 7 Jan 20 to 7 Jan 22
21 Jan: all emails from 14 Jan to 21 Jan, and not in 14 Jan 20 to 14 Jan 22
28 Jan: all emails from 21 Jan to 28 Jan, and not in 21 Jan 20 to 21 Jan 22

------------------------------******************* NEW PARTICIPANTS JAN 21********************
---Select all CH bookers that are not current members AND who have not played in last 24 months since start of year

WITH NEWCH_PARTICIPANTS1 AS
(
select distinct Contact_ID, Contact_EmailAddress 
from "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
where  BookingSessionDate BETWEEN '2020-01-01' AND '2021-01-31'
EXCEPT
select Contact_ID, Contact_EmailAddress  ,BookingSessionDate  
from  "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
where  BookingSessionDate >= (Select DATEADD(year, -2, CAST('2021-02-01' as date)))  and BookingSessionDate < '2021-02-01'
ORDER BY BookingSessionDate DESC
  )
SELECT * FROM NEWCH_PARTICIPANTS1
WHERE NEWCH_PARTICIPANTS1.Contact_EmailAddress IS NOT NULL
AND NEWCH_PARTICIPANTS1.Contact_EmailAddress NOT IN  (
select distinct Contact_EmailAddress
from  "PROD_WAREHOUSE_DB"."DWH"."VW_OCS_SESSION_REGISTRATIONS"
where Contact_EmailAddress like '%_@_%.__%'
);

-- Remove all OCS emails from the above 
-- drop table #newCH_Participants
CREATE OR REPLACE TEMPORARY TABLE DEV_WAREHOUSE_DB.DWH.NEWCH_PARTICIPANTS AS
select distinct ch.Contact_ID, ch.Contact_EmailAddress 
from DEV_WAREHOUSE_DB.DWH.NEWCH_PARTICIPANTS1 ch
where ch.Contact_EmailAddress is not null
AND ch.Contact_EmailAddress not in (
select distinct Contact_EmailAddress
from  "DEV_WAREHOUSE_DB"."DWH"."VW_OCS_SESSION_REGISTRATIONS"
where Contact_EmailAddress like '%_@_%.__%'
);


-----------------------------

SELECT state as State, YEAr as Year, DATE as Month, NEWCHPARTICANPTS as New_Participants
FROM "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE_MONTHLY"
WHERE DATE ='Mar'