----*************************************DSNW/Event report New**********

--************************************ DSNW with final post codes ranges

---STC CUP & PRE-REGISTERED
--1. SYDNEY & SURROUNDS
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
                 WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--10545

---OTHER NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE = 'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--10,499

--INTERSTATE
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND STATE <>'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--676

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--135

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND (POSTCODE IS NULL
    OR 
  POSTCODE =''
    --OR STATE ='UNKNOWN'
    OR POSTCODE NOT BETWEEN '0800' AND '7999'
     )
     ORDER BY POSTCODE
        
--6776

----TOTAL: 28631

--no of paid tickets

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND PRICE <> '0'
--8901

--no of COMP tickets

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND PRICE = '0'
--19,856


-----------------------------------------------------Corporate Hospitality

---STC CUP & PRE-REGISTERED
--1. SYDNEY & SURROUNDS
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
                 WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--86

---OTHER NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE = 'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--629

--INTERSTATE
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND STATE <>'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--109

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--0

--UNKNOWN

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND (POSTCODE IS NULL
    OR 
  POSTCODE =''
   -- OR STATE ='UNKNOWN'
    OR POSTCODE NOT BETWEEN '0800' AND '7999'
     )

--4688

----TOTAL: 

--no of paid tickets

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND PRICE <> '0'
--8901

--no of COMP tickets

SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND BOOKING_SOURCE='ARCHTICS'
AND PRICE = '0'
--19,856

--************************************************************** ATP *********************************************

---ATP CUP & PRE-REGISTERED
--1. SYDNEY & SURROUNDS
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
                 WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--24556

---OTHER NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE = 'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--31824

--INTERSTATE
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND STATE <>'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--2135

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--238

--UNKNOWN

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND (POSTCODE IS NULL
    OR 
  POSTCODE =''
    --OR STATE ='UNKNOWN'
    OR POSTCODE NOT BETWEEN '0800' AND '7999'
     )
     ORDER BY POSTCODE
        
--10532

----TOTAL: 28631

--no of paid tickets

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND PRICE <> '0'
--36714

--no of COMP tickets

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND PRICE = '0'
--33202


-----------------------------------------------------Corporate Hospitality

---STC CUP & PRE-REGISTERED
--1. SYDNEY & SURROUNDS
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2000' AND '2001' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2002' AND '2037' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2042' AND '2114' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2119' AND '2122' THEN POSTCODE
                 WHEN POSTCODE ='2126' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE ='NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--59

---OTHER NSW
WITH SYDNEY AS
(SELECT DISTINCT SUBSTR (POSTCODE,1,4) AS POSTCODE FROM 
    (SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,
            CASE WHEN POSTCODE BETWEEN '2038' AND '2041' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2115' AND '2118' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2123' AND '2125' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2127' AND '2599' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2619' AND '2898' THEN POSTCODE
                 WHEN POSTCODE BETWEEN '2921' AND '2999' THEN POSTCODE
END AS POSTCODE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE POSTCODE IS NOT NULL
)
WHERE LEN(POSTCODE)='4'
ORDER BY POSTCODE
)
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE, STATE, COUNTRY)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND POSTCODE IN (SELECT * FROM SYDNEY)
AND STATE = 'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE
--521

--INTERSTATE
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT  SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND STATE <>'NSW'
AND COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--181

--INTERNATIONAL
SELECT COUNT (DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE, POSTCODE) FROM
(
SELECT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,SUBSTR (POSTCODE, 1,4) AS POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
ORDER BY POSTCODE)
--0

--UNKNOWN

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND (POSTCODE IS NULL
    OR 
  POSTCODE =''
   -- OR STATE ='UNKNOWN'
    OR POSTCODE NOT BETWEEN '0800' AND '7999'
     )

--4823

----TOTAL: 

--no of paid tickets

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND PRICE <> '0'
--20

--no of COMP tickets

SELECT DISTINCT SEQ_ID,ROW_NAME,SEAT_NUM,EVENT_NAME,EVENT_VENUE_NAME,EVENT_DATE,POSTCODE
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"
WHERE EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND BOOKING_SOURCE='ARCHTICS'
AND PRICE = '0'
--5573

--*************************************************************************************************************************************************************************************************************

--Final query STC cup 'SYDNEY TENNIS CLASSIC'

SELECT A.NAME,A.EVENT_DATE,A.EVENT_SESSION,A.TICKET_TYPE,A.POSTCODE,A.COUNTRY,SUM(A.QUANTITY) AS TICKET_QUANTITY, A.REVENUE,A.PURCHASE_DATE, A.PURCHASE_CHANNEL FROM
(
SELECT DISTINCT  T.SEQ_ID,T.CUST_NAME_ID,CONCAT(T.FIRST_NAME,' ',T.LAST_NAME) AS NAME,T.ROW_NAME,T.SEAT_NUM,T.EVENT_NAME AS EVENT_SESSION,T.EVENT_DATE,T.QUANTITY, T.PRICE AS REVENUE, T.TRANSACTION_DATE AS PURCHASE_DATE,--C.PRICE_CATEGORY_NAME_DESC,
T.POSTCODE, T.COUNTRY,T.PRICE_CATEGORY_NAME,
CASE WHEN PRICE <> 0 THEN 'PAID'
     WHEN PRICE = 0 THEN 'COMP' 
     ELSE 'NA'
     END AS TICKET_TYPE,
CASE WHEN TRANSACTION_DATE = EVENT_DATE THEN 'On-Site Purchase'
     WHEN TRANSACTION_DATE < EVENT_DATE THEN 'Pre-Purchased'
     ELSE 'NA'
     END AS PURCHASE_CHANNEL
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" T
WHERE T.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND T.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
) A
GROUP BY A.NAME,A.EVENT_DATE,A.EVENT_SESSION,A.TICKET_TYPE,A.POSTCODE,A.COUNTRY,A.REVENUE,A.PURCHASE_DATE, A.PURCHASE_CHANNEL
 
----ATP CUP

SELECT A.NAME,A.EVENT_DATE,A.EVENT_SESSION,A.TICKET_TYPE,A.POSTCODE,A.COUNTRY,SUM(A.QUANTITY) AS TICKET_QUANTITY, A.REVENUE,A.PURCHASE_DATE, A.PURCHASE_CHANNEL FROM
(
SELECT DISTINCT  T.SEQ_ID,T.CUST_NAME_ID,CONCAT(T.FIRST_NAME,' ',T.LAST_NAME) AS NAME,T.ROW_NAME,T.SEAT_NUM,T.EVENT_NAME AS EVENT_SESSION,
  T.EVENT_DATE,T.QUANTITY, T.PRICE AS REVENUE, T.TRANSACTION_DATE AS PURCHASE_DATE,--C.PRICE_CATEGORY_NAME_DESC,
T.POSTCODE, T.COUNTRY,T.PRICE_CATEGORY_NAME,
CASE WHEN PRICE <> 0 THEN 'PAID'
     WHEN PRICE = 0 THEN 'COMP' 
     ELSE 'NA'
     END AS TICKET_TYPE,
CASE WHEN TRANSACTION_DATE = EVENT_DATE THEN 'On-Site Purchase'
     WHEN TRANSACTION_DATE < EVENT_DATE THEN 'Pre-Purchased'
     ELSE 'NA'
     END AS PURCHASE_CHANNEL
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" T
WHERE T.EVENT_TOURNAMENT_NAME LIKE 'ATP CUP%'
AND T.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
) A
--WHERE EVENT_SESSION NOT IN ('EATP_5JAN2022N','EATP_1JAN2022D','EATP_1JAN2022N','EATP_2JAN2022N','EATP_4JAN2022N','EATP_4JAN2022D','EATP_3JAN2022N','EATP_3JAN2022D','EATP_6JAN2022N','EATP_2JAN2022D','EATP_5JAN2022D',                            'EATP_6JAN2022D')
GROUP BY A.NAME,A.EVENT_DATE,A.EVENT_SESSION,A.TICKET_TYPE,A.POSTCODE,A.COUNTRY,A.REVENUE,A.PURCHASE_DATE, A.PURCHASE_CHANNEL

-----69596