--******************************************Economic Impact Report Final***************

---'ADELAIDE INTERNATIONAL' : SA
---'ATP CUP' : NSW
---'STC CUP' : NSW

---****** Sydney Event : STC CUP
--GENERAL ATTENDEES ONLINE

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'

--28757, addition of below: 23492

-- SYDNEY LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND PC.MMM_2019 ='1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--20638, 87.85%

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--2191, 9.32%

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND PC.STATE <>'NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--619, 2.63%

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--135, 0.57%



---****** Sydney Event : STC CUP
--COMP TICKETS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.PRICE ='0'

--19856, addition of below: 14996

-- SYDNEY LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.PRICE ='0'
AND PC.MMM_2019 ='1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--13187, 87.93

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.PRICE ='0'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1408, 9.38

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.PRICE ='0'
AND PC.STATE <>'NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--374, 2.49

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'SYDNEY TENNIS CLASSIC'
AND RT.PRICE ='0'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--27, 0.18

--OTHER: 24.54%

--*********************ATP CUP****************************
---****** Sydney Event : ATP CUP
--GENERAL ATTENDEES ONLINE

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'

--50883, addition of below: 44472

-- SYDNEY LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND PC.MMM_2019 ='1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--39514, 88.85

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--3339, 7.50

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND PC.STATE <>'NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1427, 3.20

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--192, 0.43


---****** Sydney Event : ATP CUP
--COMP TICKETS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.PRICE ='0'

--24646, addition of below: 18670

-- SYDNEY LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.PRICE ='0'
AND PC.MMM_2019 ='1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--16693, 89.41

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.PRICE ='0'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1228, 6.57

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.PRICE ='0'
AND PC.STATE <>'NSW'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--694, 3.71

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ATP CUP'
AND RT.PRICE ='0'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--55, 0.29


--*********************ADELAIDE INTERNATIONAL****************************
---****** SA Event : ADELAIDE INTERNATIONAL
--GENERAL ATTENDEES ONLINE

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'

--33663, addition of below: 24223

-- ADELAIDE LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS ADELAIDE_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND PC.MMM_2019 ='1'
AND PC.STATE ='SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--19610, 80.95%

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--2754, 11.36%

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND PC.STATE <>'SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1787, 7.37%

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--72, 0.32%

---****** SA Event : ADELAIDE INTERNATIONAL
--COMP TICKETS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.PRICE ='0'

--16615, addition of below: 8177

-- ADELAIDE LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.PRICE ='0'
AND PC.MMM_2019 ='1'
AND PC.STATE ='SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--6944, 84.92%

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.PRICE ='0'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1004, 12.27%

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.PRICE ='0'
AND PC.STATE <>'SA'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--209, 2.55%

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'ADELAIDE INTERNATIONAL'
AND RT.PRICE ='0'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--20, 0.24%

--************************************************** AO

---****** AO
--GENERAL ATTENDEES ONLINE

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'

--560795, addition of below: 437080

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--282083, 64.56

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND PC.MMM_2019 <>'1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--38802, 8.87

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--108347, 24.78

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--7848, 1.79




--COMP TICKETS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.PRICE ='0'

--95258, addition of below: 33508

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.PRICE ='0'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--26340, 78.60

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.PRICE ='0'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1678, 5

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.PRICE ='0'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--4622, 13.79

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.PRICE ='0'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--868, 2.59

--------Hospitality Tickets --ARCHTICS

select distinct booking_source FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING"


SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.BOOKING_SOURCE='ARCHTICS'

--150529, addition of below: 75673

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--49415, 65.30

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1691, 2.23

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--21226, 28.04

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'AUSTRALIAN OPEN'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--3341, 4.41

SELECT DISTINCT EVENT_TOURNAMENT_NAME FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" --MELBOURNE SUMMER SERIES
-----********************************************************** MSS Breakdown ****************
--GENERAL ATTENDEES ONLINE

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'

--33907, addition of below: 31084

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--27407

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND PC.MMM_2019 <>'1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--2387

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--1145

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--145




--COMP TICKETS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.PRICE ='0'

--11453, addition of below: 10023

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.PRICE ='0'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--9000

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.PRICE ='0'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--672

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.PRICE ='0'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--317

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.PRICE ='0'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--34

--------Hospitality Tickets --ARCHTICS

SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID, ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE)
FROM "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.BOOKING_SOURCE='ARCHTICS'

--721, addition of below: 118

-- MEL LOCAL TICKETS 
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS SYDNEY_LOCAL_ATTENDEES
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.MMM_2019 ='1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--114

--INTRASTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTRASTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.MMM_2019 <> '1'
AND PC.STATE ='VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--0

--INTERSTATE
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND PC.STATE <>'VIC'
AND RT.COUNTRY  IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--4

-- OVER
SELECT COUNT(DISTINCT SEQ_ID,CUST_NAME_ID,ROW_NAME,SEAT_NUM,EVENT_VENUE_NAME,EVENT_DATE) AS INTERSTATE
FROM  "PROD_WAREHOUSE_DB"."DWH"."REPORTING_TICKETING" RT
LEFT JOIN "PROD_WAREHOUSE_DB"."DWH"."DIM_AUS_POST_CODE" PC
ON RT.POSTCODE = PC.POSTCODE
WHERE RT.EVENT_TOURNAMENT_SERIES_YEAR ='2022'
AND RT.EVENT_TOURNAMENT_NAME = 'MELBOURNE SUMMER SERIES'
AND RT.BOOKING_SOURCE='ARCHTICS'
AND RT.COUNTRY NOT IN ('AU', 'AUSTRALIA', 'AUSTALIA','AUS')
--0