----********************************Power BI report queries********************************

--Monthly performance dashboard
SELECT 
CASE WHEN STATE ='Australian Capital Territory' THEN 'ACT'
     WHEN STATE ='New South Wales' THEN 'NSW'
     WHEN STATE ='Northern Territory' THEN 'NT'
     WHEN STATE ='Queensland' THEN 'QLD'
     WHEN STATE ='South Australia' THEN 'SA'
     WHEN STATE ='Tasmania' THEN 'TAS'
     WHEN STATE ='Victoria' THEN 'VIC'
     WHEN STATE ='Western Australia' THEN 'WA'
END AS COURT_HIRE ,
COUNT(DISTINCT BOOKINGSESSION_ID) AS BOOKINGS_JAN_21
FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE_YEAR ='2021'
AND BOOKINGSESSIONDATE_MONTH ='Jan'
AND STATE IN ('Australian Capital Territory','Victoria','Tasmania')
GROUP BY COURT_HIRE

--Jan 21 - 52897
--Jan 22 - 70476

SELECT STATE AS COURT_HIRE, COUNT(DISTINCT BOOKINGSESSION_ID) AS BOOKINGS_JAN_21 FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE_YEAR ='2021'
AND BOOKINGSESSIONDATE_MONTH ='Jan' 
GROUP BY STATE
ORDER BY STATE

SELECT STATE AS COURT_HIRE, COUNT(DISTINCT BOOKINGSESSION_ID) AS BOOKINGS_JAN_22 FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE_YEAR ='2022'
AND BOOKINGSESSIONDATE_MONTH ='Jan' 
GROUP BY STATE
ORDER BY 1

SELECT STATE AS COURT_HIRE, COUNT(DISTINCT LOWER(CONTACT_EMAILADDRESS)) AS UNIQUE_BOOKERS_JAN_21 FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE_YEAR ='2021'
AND BOOKINGSESSIONDATE_MONTH ='Jan' 
GROUP BY STATE

SELECT STATE AS COURT_HIRE, COUNT(DISTINCT LOWER(CONTACT_EMAILADDRESS)) AS UNIQUE_BOOKERS_JAN_22 FROM "PROD_WAREHOUSE_DB"."DWH"."VW_COURT_HIRE_CASUALBOOKINGS"
WHERE BOOKINGSESSIONDATE_YEAR ='2022'
AND BOOKINGSESSIONDATE_MONTH ='Jan' 
GROUP BY STATE


----KPI Dashborad queries

select SUM(NEWCHPARTICANPTS) from "DEV_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE_WEEKLY"
WHERE DATE LIKE '%2022-02%'


select * from "DEV_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_OCS_WEEKLY";

select sum(NEWCHPARTICANPTS),date
from "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE"
where date = '2022-01-31'
group by date

--------------------------------***********************COST REPORT QUERIES*******************************

SELECT *
FROM "ADMIN_DB"."OPERATIONAL_DASHBOARD"."VW_SNOWFLAKE_COMPUTE_COSTS"
WHERE START_DATE LIKE '%2022-02%'
--ORDER BY START_DATE DESC

select sum(NEWCHPARTICANPTS)
from "PROD_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_COURT_HIRE"
where date ='2022-02-07'

select sum(NEWOCSPARTICANPTS) from "DEV_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_OCS_SINGLE"
where date ='2022-02-17'

SELECT * FROM "DEV_WAREHOUSE_DB"."DWH"."RPT_NEW_PARTICIPANTS_OCS_SINGLE"

SELECT SUM(SF_DAILY_AVERAGE_COST) FROM
(
SELECT SF_DAILY_AVERAGE_COST,DATE FROM "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_SA_COST_REPORT"
WHERE DATE LIKE '%2022-02%'
  )
--GROUP BY DATE

SELECT SUM(AZURE_DAILY_AVERAGE_COST) FROM  "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_SA_COST_REPORT"
WHERE DATE LIKE '%2022-02%' --32.45

SELECT SF_MONTHLY_COST_TO_DATE FROM  "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_SA_COST_REPORT"
WHERE DATE = (SELECT MAX(DATE) FROM  "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_SA_COST_REPORT")

SELECT * FROM  "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_SA_COST_REPORT"
WHERE DATE LIKE '%2022-02%'

SELECT * FROM "ADMIN_DB"."OPERATIONAL_DASHBOARD"."V_AZURE_DAILY_COST"
WHERE DATE LIKE '%2022-02%'